### ISSUE TITLE
HW 02 graded

### ISSUE THREAD

**Issue by mtaylor-semo** [gabd-students/alam_afreen#1]
Good job on HW02. I have the following comment.

### From part 2, vectors

```
# Find the maximum value in cultures_without_pplo and cultures_without_pplo
max(cultures_without_pplo)
max(cultures_with_pplo)
# Answer comes out to be 5.8 and 4.9 respectively.
# Note that the above functions could be directly substituted in place of the corresponding values but functions are run and values are found since instructions explicitly state to 'find the value'.
# Store in max_without_pplo and max_with_pplo, respectively.
max_without_pplo <- 5.8
max_with_pplo <- 4.9
```
Your statement about using the functions directly is the proper way to go. Never hard code a value when R will do the work for you. You would not be in violation of the instructions with this code:
```
max_without_pplo <- max(cultures_without_pplo).
```
The `max()` function is finding the value for you, as you recognized. Same goes for `min()` or any other function.

**Comment by afreenalam** [comment]
I will keep this in mind for further assignments.
Thank you
