### ISSUE TITLE
HW07 graded

### ISSUE THREAD

**Issue by mtaylor-semo** [gabd-students/alam_afreen#2]
Didn't have code to import the roseate tern data. I had to add it.

Didn't remove the blennioides record with missing data for the darter graphs.

Other than that, well done!

**Comment by afreenalam** [comment]
I  added the missing codes after grading for future reference.  Do we always have to 'drop_na' while making a geom plot even thought it does it on its own (just gives a ⚠)?

**Comment by mtaylor-semo** [comment]
Hi Afreen,

Yes, as a general rule, you want to control when NAs are being removed by your code so you don't have any surprises.


Mike
--
Dr. Michael S. Taylor
Professor of Biology

Dept. of Biology, MS 6200

Southeast Missouri State University
Cape Girardeau, MO 63701

mtaylor@semo.edu<mailto:mtaylor@semo.edu>
(573) 651-2357
Rhodes 217
________________________________

**Comment by afreenalam** [comment]
Thank you, I will keep this in mind !
